### ISSUE TITLE
Better commit messages

### ISSUE THREAD

**Issue by vmpyr** [RajNethikar13/B-Lipase#1]
I have noticed that the commit messages on this repo are very just the default ones that git provides. This is not good practice. It seems like you are using `Git Desktop` or the `GitHub web-app` itself for committing your changes. There is nothing wrong in the that, but it would really help you if you take a quick [git basics](https://www.youtube.com/watch?v=8JJ101D3knE) tutorial and incorporate it into your workflow

Try to write better commit messages so that you can refer to them when you want and understand the changes behind each commit. Refer to [this article](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/) for help.

**Comment by RajNethikar13** [comment]
k
